## Sampling Used In SMACD 18 Article for the VCOTA

The results are not an exact match to the article as the code and models were updated to newer versions of tensorflow and keras.

In [1]:
import joblib
import numpy as np
import tensorflow.keras as k
import matplotlib.pyplot as plt


from circuit_net import *

2022-03-24 21:33:39.367166: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-24 21:33:39.367204: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
#load vcota models

vcota_plain1  = build_dense_model((15, 480, 240, 60, 12), activation='relu', l2_lambda=2e-5)
vcota_plain1.load_weights('../models/smacd18/CircuitNet-VCOTA-v1_15_480_240_60_12-201803131213.h5')

vcota_plain = build_dense_model((15, 120, 240, 60, 12), activation='relu', l2_lambda=1.3e-5)
vcota_plain.load_weights('../models/smacd18/CircuitNet-VCOTA-v1-201803121010.h5')

vcota_plain_scalers = {
    "X_poly": joblib.load('../models/smacd18/VCOTA_X_poly.pkl'), 
    "X_scaler": joblib.load('../models/smacd18/VCOTA_X_scaler.pkl'), 
    "Y_scaler": joblib.load('../models/smacd18/VCOTA_Y_scaler.pkl')}


vcota_aug = build_dense_model((15, 120, 240, 60, 12), activation='relu', l2_lambda=1.3e-5)
vcota_aug.load_weights('../models/smacd18/CircuitNet-VCOTA-augmented_long_train-201803111533.h5')

vcota_aug_tl = build_dense_model((15, 120, 240, 60, 12), activation='relu', l2_lambda=1.3e-5)
vcota_aug_tl.load_weights('../models/smacd18/CircuitNet-VCOTA-augmented_transferlearn-201803131552.h5')

vcota_aug_scalers = {
    "X_poly": joblib.load('../models/smacd18/VCOTAaug_X_poly.pkl'), 
    "X_scaler": joblib.load('../models/smacd18/VCOTAaug_X_scaler.pkl'), 
    "Y_scaler": joblib.load('../models/smacd18/VCOTAaug_Y_scaler.pkl')}


2022-03-24 21:33:43.973944: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-03-24 21:33:43.976942: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-24 21:33:43.978222: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-BHJQ8M4): /proc/driver/nvidia/version does not exist
2022-03-24 21:33:43.986853: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
#labels and ranges matching the nelist names
lablels = ['_w8','_w6','_w4','_w10','_w1','_w0','_l8','_l6','_l4','_l10','_l1','_l0']
minVal  = [0.6e-6,0.6e-6,0.6e-6,0.6e-6,0.6e-6,0.6e-6,0.3e-6,0.3e-6,0.3e-6,0.3e-6,0.3e-6,0.3e-6]
maxVal  = [10e-4,10e-4,10e-4,10e-4,10e-4,10e-4,5e-5,5e-5,5e-5,5e-5,5e-5,5e-5]

In [4]:
wishlist = np.array([
    [50, 300e-6, 60e6, 65],
    [50, 600e-6, 60e6, 65],
    [80, 300e-6, 60e6, 65],
    [40, 600e-6, 160e6, 65],
])

print (format_circuit(predict_circuit(wishlist,vcota_plain1, vcota_plain_scalers, True),lablels))
print (format_circuit(predict_circuit(wishlist,vcota_aug, vcota_aug_scalers, True),lablels))
print (format_circuit(predict_circuit(wishlist,vcota_aug_tl, vcota_aug_scalers, True),lablels))

Design Variables
----
_w8 = 1.0016618e-06
_w6 = 6.930609e-05
_w4 = 2.1433438e-05
_w10 = 1.09245175e-05
_w1 = 5.4767725e-06
_w0 = 6.8837806e-05
_l8 = 9.316899e-07
_l6 = 8.2123455e-07
_l4 = 7.583163e-07
_l10 = 8.413006e-07
_l1 = 3.0279134e-07
_l0 = 5.2297486e-07
----
Design Variables
----
_w8 = 1.0663082e-06
_w6 = 8.144413e-05
_w4 = 5.1202496e-05
_w10 = 6.93186e-06
_w1 = 5.4852742e-05
_w0 = 0.00012529093
_l8 = 3.9333332e-07
_l6 = 4.955453e-07
_l4 = 5.6502665e-07
_l10 = 8.154691e-07
_l1 = 5.173905e-07
_l0 = 7.850064e-07
----
Design Variables
----
_w8 = 1.0322602e-06
_w6 = 0.00055183814
_w4 = 0.000101688966
_w10 = -9.753081e-07
_w1 = 1.0537862e-07
_w0 = -2.7333333e-05
_l8 = 1.435265e-06
_l6 = 5.0243366e-06
_l4 = 4.1654807e-06
_l10 = 2.7825736e-06
_l1 = 3.9908042e-07
_l0 = 1.4483944e-06
----
Design Variables
----
_w8 = 1.0073127e-06
_w6 = 0.00013781106
_w4 = 2.6954529e-05
_w10 = 9.025805e-06
_w1 = 1.1041844e-05
_w0 = 3.9738763e-05
_l8 = 1.0650284e-06
_l6 = 1.389017e-06
_l4 = 1.2883597e-06
_

In [5]:
#sample the models and generate the design variables that are going to be simulated
wishlist = np.array([
    [50, 300e-6, 60e6, 65],
    [50, 600e-6, 60e6, 65],
    [80, 300e-6, 60e6, 65],
    [40, 600e-6, 160e6, 65],
])

print (format_circuit(predict_circuit(wishlist,vcota_plain1, vcota_plain_scalers, True),lablels))
print (format_circuit(predict_circuit(wishlist,vcota_aug, vcota_aug_scalers, True),lablels))
print (format_circuit(predict_circuit(wishlist,vcota_aug_tl, vcota_aug_scalers, True),lablels))


Design Variables
----
_w8 = 1.0016618e-06
_w6 = 6.930609e-05
_w4 = 2.1433438e-05
_w10 = 1.09245175e-05
_w1 = 5.4767725e-06
_w0 = 6.8837806e-05
_l8 = 9.316899e-07
_l6 = 8.2123455e-07
_l4 = 7.583163e-07
_l10 = 8.413006e-07
_l1 = 3.0279134e-07
_l0 = 5.2297486e-07
----
Design Variables
----
_w8 = 1.0663082e-06
_w6 = 8.144413e-05
_w4 = 5.1202496e-05
_w10 = 6.93186e-06
_w1 = 5.4852742e-05
_w0 = 0.00012529093
_l8 = 3.9333332e-07
_l6 = 4.955453e-07
_l4 = 5.6502665e-07
_l10 = 8.154691e-07
_l1 = 5.173905e-07
_l0 = 7.850064e-07
----
Design Variables
----
_w8 = 1.0322602e-06
_w6 = 0.00055183814
_w4 = 0.000101688966
_w10 = -9.753081e-07
_w1 = 1.0537862e-07
_w0 = -2.7333333e-05
_l8 = 1.435265e-06
_l6 = 5.0243366e-06
_l4 = 4.1654807e-06
_l10 = 2.7825736e-06
_l1 = 3.9908042e-07
_l0 = 1.4483944e-06
----
Design Variables
----
_w8 = 1.0073127e-06
_w6 = 0.00013781106
_w4 = 2.6954529e-05
_w10 = 9.025805e-06
_w1 = 1.1041844e-05
_w0 = 3.9738763e-05
_l8 = 1.0650284e-06
_l6 = 1.389017e-06
_l4 = 1.2883597e-06
_

In [6]:
#sample the models and generate the design variables that are going to be simulated
wishlist = augment_specs(np.array([[50, 300e-6, 60e6, 65]]),
    np.array([1,-1, 1, 1]), 
    20, 0.05
)

print (wishlist)

with open("../results/vcota_plain1_predictions.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_plain1, vcota_plain_scalers, True),lablels), file=text_file)
    
with open("../results/vcota_aug_predictions.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_aug, vcota_aug_scalers, True),lablels), file=text_file)

with open("../results/vcota_aug_tl_predictions.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_aug_tl, vcota_aug_scalers, True),lablels), file=text_file)

[[5.00000000e+01 3.00000000e-04 6.00000000e+07 6.50000000e+01]
 [5.10562862e+01 2.88166649e-04 6.09523883e+07 6.55236030e+01]
 [5.24689718e+01 2.90051572e-04 6.01833124e+07 6.55676457e+01]
 [5.15781398e+01 2.89661178e-04 6.20295668e+07 6.80555042e+01]
 [5.07804847e+01 2.90521383e-04 6.06952559e+07 6.81632241e+01]
 [5.20082998e+01 2.98884968e-04 6.17951617e+07 6.81024525e+01]
 [5.18954941e+01 2.86838974e-04 6.23761873e+07 6.61109320e+01]
 [5.11371495e+01 2.88419418e-04 6.12845873e+07 6.76260354e+01]
 [5.03540736e+01 2.98707697e-04 6.25549447e+07 6.58150346e+01]
 [5.19003622e+01 2.97413563e-04 6.12617619e+07 6.71829090e+01]
 [5.01262571e+01 2.90860869e-04 6.05974894e+07 6.66185561e+01]
 [5.09515380e+01 2.87617952e-04 6.16487436e+07 6.75397204e+01]
 [5.10774647e+01 2.96288412e-04 6.04693334e+07 6.81271079e+01]
 [5.02815361e+01 2.94426021e-04 6.03547951e+07 6.64928539e+01]
 [5.18178504e+01 2.95969605e-04 6.23417125e+07 6.76905124e+01]
 [5.12697494e+01 2.91759342e-04 6.03958455e+07 6.538776

In [7]:
#sample the models and generate the design variables that were  simulated

wishlist = augment_specs(np.array([[45, 800e-6, 100e6, 55]]),
    np.array([1,-1, 1, 1]), 
    100, 0.25
)

print (wishlist)

#with open("../results/vcota_plain1_predictions_offGBW1.log", "w") as text_file:
#    print (format_circuit(predict_circuit(wishlist,vcota_plain1, vcota_plain_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)
    
with open("../results/vcota_aug_predictions_offGBW_1.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_aug, vcota_aug_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)

#with open("../results/vcota_aug_tl_predictions_offGBW.log", "w") as text_file:
#    print (format_circuit(predict_circuit(wishlist,vcota_aug_tl, vcota_aug_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)

[[4.50000000e+01 8.00000000e-04 1.00000000e+08 5.50000000e+01]
 [5.20229590e+01 6.68987940e-04 1.15246610e+08 6.72280120e+01]
 [4.89868406e+01 6.60847350e-04 1.22966129e+08 5.93632253e+01]
 [5.42647712e+01 6.76906425e-04 1.06370633e+08 5.68226224e+01]
 [5.25197027e+01 6.02832647e-04 1.09091298e+08 6.25828647e+01]
 [5.23508228e+01 7.91469269e-04 1.13419935e+08 6.64587122e+01]
 [4.70257357e+01 6.36608656e-04 1.11239667e+08 6.29848501e+01]
 [5.07170522e+01 7.08633640e-04 1.04511549e+08 5.97533749e+01]
 [4.86949629e+01 6.05265878e-04 1.09148819e+08 5.93116304e+01]
 [5.47094356e+01 7.01384338e-04 1.23734732e+08 5.58415319e+01]
 [5.18069270e+01 7.08355844e-04 1.12098075e+08 6.44410307e+01]
 [4.56953861e+01 7.96788445e-04 1.11933354e+08 5.77752986e+01]
 [4.55350187e+01 7.65662818e-04 1.17928777e+08 5.59762400e+01]
 [4.94399491e+01 6.10407432e-04 1.13099590e+08 6.35997325e+01]
 [4.55649297e+01 6.70118349e-04 1.02227900e+08 5.98050569e+01]
 [5.22304890e+01 7.00828130e-04 1.24101056e+08 6.843165

In [8]:
#sample the models and generate the design variables that were simulated

wishlist = augment_specs(np.array([[50, 150e-6, 30e6, 65]]),
    np.array([1,-1, 1, 1]), 
    100, 0.15
)

with open("../results/vcota_plain_predictions_offGDC.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_plain, vcota_plain_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)

with open("../results/vcota_plain_predictions_offGDC1.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_plain1, vcota_plain_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)
    
    
with open("../results/vcota_aug_predictions_offGDC.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_aug, vcota_aug_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)

with open("../results/vcota_aug_tl_predictions_offGDC.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_aug_tl, vcota_aug_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)

In [9]:
#sample the models and generate the design variables that were simulated
wishlist = augment_specs(np.array([[50, 150e-6, 20e6, 70]]),
    np.array([1,-1, 1, 1]), 
    40, 0.5
)

print (wishlist)

with open("../results/vcota_plain_predictions_offIDD.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_plain1, vcota_plain_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)
    
with open("../results/vcota_aug_predictions_offIDD.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_aug, vcota_aug_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)

with open("../results/vcota_aug_tl_predictions_offIDD.log", "w") as text_file:
    print (format_circuit(predict_circuit(wishlist,vcota_aug_tl, vcota_aug_scalers, True),lablels, minVal=minVal, maxVal=maxVal), file=text_file)

[[5.00000000e+01 1.50000000e-04 2.00000000e+07 7.00000000e+01]
 [5.83075965e+01 1.11283877e-04 2.78774169e+07 7.27837278e+01]
 [5.67964263e+01 1.14706856e-04 2.59226364e+07 7.75883789e+01]
 [7.01635129e+01 1.38315594e-04 2.40900705e+07 9.44812203e+01]
 [7.34732882e+01 7.73205596e-05 2.15915555e+07 8.51679735e+01]
 [6.06741556e+01 1.23514669e-04 2.00474363e+07 7.10613480e+01]
 [6.51088663e+01 1.41610194e-04 2.42881885e+07 1.00403355e+02]
 [6.85200578e+01 1.13158801e-04 2.64829425e+07 8.86859073e+01]
 [6.47549624e+01 1.44281571e-04 2.52324137e+07 1.03974510e+02]
 [6.25665388e+01 1.27867336e-04 2.79431105e+07 9.61478060e+01]
 [6.44459237e+01 1.12336080e-04 2.97062277e+07 9.97922057e+01]
 [7.39721357e+01 1.48496175e-04 2.48270540e+07 9.04709478e+01]
 [6.75762133e+01 1.21623776e-04 2.85367644e+07 1.04143288e+02]
 [6.34440314e+01 1.28407977e-04 2.82688890e+07 8.52202827e+01]
 [5.12305357e+01 1.01659424e-04 2.49595797e+07 1.03113816e+02]
 [7.40480907e+01 1.13164131e-04 2.45035651e+07 8.978992

<small>Copyright (c) 2022 Nuno Lourenço - Instituto de Telecomunicações.</small>